name: Test pages deployment

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docsite/**'


jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./docsite
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: './docsite/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
      - name: Test build website
        run: pnpm run build
