name: testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_test:
    timeout-minutes: 5
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          npm -g install @abaplint/transpiler-cli
          npm install @abaplint/runtime
          rm -rf transpiled
          echo "Building ..."
          abap_transpile transpile_for_testing.json
          echo "Running unit tests ..."
          node transpiled/index.mjs
